In [3]:
from tensorflow import keras
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import numpy as np

import cv2

In [23]:
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

In [5]:
x_train.shape,x_test.shape

((50000, 32, 32, 3), (10000, 32, 32, 3))

In [6]:
nsamples, nx, ny, nrgb = x_train.shape
x_train2 = x_train.reshape((nsamples,nx*ny*nrgb))

In [7]:
nsamples, nx, ny, nrgb = x_test.shape
x_test2 = x_test.reshape((nsamples,nx*ny*nrgb))

In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
model=RandomForestClassifier()

In [24]:
model.fit(x_train2, y_train)

c:\Users\chaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [25]:
y_pred=model.predict(x_test2)
y_pred

array([2, 8, 8, ..., 5, 5, 7], dtype=uint8)

In [26]:
accuracy_score(y_pred,y_test)
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.55      0.54      0.55      1027
           1       0.57      0.52      0.54      1093
           2       0.33      0.37      0.35       894
           3       0.28      0.33      0.30       837
           4       0.38      0.39      0.39       967
           5       0.40      0.43      0.41       933
           6       0.57      0.48      0.52      1201
           7       0.46      0.52      0.49       881
           8       0.59      0.57      0.58      1031
           9       0.55      0.48      0.51      1136

    accuracy                           0.47     10000
   macro avg       0.47      0.46      0.46     10000
weighted avg       0.48      0.47      0.47     10000



In [27]:
confusion_matrix(y_pred,y_test)

array([[554,  40,  98,  56,  53,  35,  11,  42,  92,  46],
       [ 46, 566,  50,  41,  25,  27,  35,  42,  94, 167],
       [ 62,  18, 327,  86, 173,  73,  70,  53,  18,  14],
       [ 18,  33,  84, 276,  52, 165,  74,  66,  33,  36],
       [ 32,  19, 135,  73, 379,  73, 118,  97,  19,  22],
       [ 17,  28,  69, 183,  49, 397,  57,  76,  36,  21],
       [ 21,  31, 129, 131, 144,  85, 571,  49,  10,  30],
       [ 28,  36,  62,  61,  79,  83,  19, 459,  21,  33],
       [163,  59,  25,  24,  22,  34,   7,  26, 590,  81],
       [ 59, 170,  21,  69,  24,  28,  38,  90,  87, 550]], dtype=int64)

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
knn=KNeighborsClassifier(n_neighbors=7)

In [30]:
knn.fit(x_train2,y_train)

c:\Users\chaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=7)

In [31]:
y_pred_knn=knn.predict(x_test2)
y_pred_knn

array([2, 8, 8, ..., 5, 6, 4], dtype=uint8)

In [32]:
accuracy_score(y_pred_knn,y_test)
print(classification_report(y_pred_knn,y_test))

              precision    recall  f1-score   support

           0       0.52      0.40      0.45      1299
           1       0.20      0.70      0.30       280
           2       0.44      0.22      0.29      2013
           3       0.20      0.28      0.23       707
           4       0.52      0.23      0.32      2222
           5       0.20      0.40      0.27       504
           6       0.27      0.35      0.30       761
           7       0.20      0.70      0.31       281
           8       0.69      0.39      0.50      1749
           9       0.14      0.73      0.23       184

    accuracy                           0.34     10000
   macro avg       0.34      0.44      0.32     10000
weighted avg       0.45      0.34      0.35     10000



In [33]:
confusion_matrix(y_pred_knn,y_test)

array([[518, 118, 110,  66,  60,  63,  22,  78, 112, 152],
       [  7, 195,   2,   5,   0,   2,   1,   8,  10,  50],
       [118, 124, 437, 243, 268, 225, 271, 185,  47,  95],
       [ 12,  51,  50, 199,  33, 156,  56,  57,  34,  59],
       [ 46, 173, 250, 214, 521, 201, 319, 294,  69, 135],
       [  5,  32,  24, 102,  14, 204,  32,  60,  12,  19],
       [ 30,  55,  65, 108,  44,  80, 265,  48,  14,  52],
       [  5,   8,   7,  11,  11,  10,   1, 196,   7,  25],
       [255, 223,  53,  51,  48,  53,  32,  68, 688, 278],
       [  4,  21,   2,   1,   1,   6,   1,   6,   7, 135]], dtype=int64)

In [41]:
from sklearn.tree import DecisionTreeClassifier

In [42]:
dtc=DecisionTreeClassifier()

In [43]:
dtc.fit(x_train2,y_train)

DecisionTreeClassifier()

In [44]:
y_pred_dtc=dtc.predict(x_test2)
y_pred_dtc

array([7, 1, 9, ..., 2, 5, 1], dtype=uint8)

In [45]:
accuracy_score(y_pred_dtc,y_test)
print(classification_report(y_pred_dtc,y_test))

              precision    recall  f1-score   support

           0       0.35      0.33      0.34      1067
           1       0.26      0.28      0.27       931
           2       0.20      0.20      0.20      1012
           3       0.19      0.19      0.19       990
           4       0.23      0.22      0.22      1056
           5       0.22      0.22      0.22       982
           6       0.26      0.26      0.26       994
           7       0.27      0.28      0.27       966
           8       0.39      0.38      0.39      1023
           9       0.28      0.29      0.28       979

    accuracy                           0.27     10000
   macro avg       0.27      0.27      0.27     10000
weighted avg       0.27      0.27      0.27     10000



In [46]:
confusion_matrix(y_pred_dtc,y_test)

array([[355,  79,  96,  70,  59,  56,  41,  78, 144,  89],
       [ 75, 263,  52,  51,  43,  52,  55,  80,  96, 164],
       [ 73,  61, 205, 106, 156,  99, 137,  77,  46,  52],
       [ 45,  86, 101, 189,  96, 154, 118,  93,  43,  65],
       [ 64,  65, 140, 107, 228,  96, 152,  98,  50,  56],
       [ 52,  50, 121, 132, 104, 216,  96, 105,  50,  56],
       [ 39,  55, 115, 143, 130, 111, 260,  66,  25,  50],
       [ 62,  65,  84,  90, 107,  99,  57, 269,  45,  88],
       [161, 109,  32,  52,  32,  64,  26,  57, 391,  99],
       [ 74, 167,  54,  60,  45,  53,  58,  77, 110, 281]], dtype=int64)

In [47]:
from sklearn.naive_bayes import GaussianNB

In [48]:
nb=GaussianNB()

In [49]:
nb.fit(x_train2,y_train)

c:\Users\chaga\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [50]:
y_pred_nb=nb.predict(x_test2)
y_pred_nb

array([6, 8, 8, ..., 6, 5, 4], dtype=uint8)

In [51]:
accuracy_score(y_pred_nb,y_test)
print(classification_report(y_pred_nb,y_test))

              precision    recall  f1-score   support

           0       0.49      0.27      0.35      1817
           1       0.17      0.41      0.24       405
           2       0.08      0.19      0.12       443
           3       0.08      0.25      0.12       305
           4       0.42      0.24      0.30      1737
           5       0.26      0.31      0.29       840
           6       0.47      0.25      0.33      1846
           7       0.13      0.42      0.20       310
           8       0.47      0.39      0.42      1219
           9       0.41      0.38      0.39      1078

    accuracy                           0.30     10000
   macro avg       0.30      0.31      0.28     10000
weighted avg       0.39      0.30      0.32     10000



In [52]:
confusion_matrix(y_pred_nb,y_test)

array([[494, 141, 225, 163,  86, 156, 106, 134, 168, 144],
       [ 20, 166,  24,  36,   8,  17,   2,  24,  41,  67],
       [ 39,  24,  83,  54,  57,  55,  60,  36,  18,  17],
       [ 10,  31,  15,  76,  26,  51,  18,  41,  17,  20],
       [ 84,  66, 292, 151, 417, 167, 228, 228,  56,  48],
       [ 34,  72,  48, 129,  38, 264,  46,  94,  83,  32],
       [ 50, 192, 209, 262, 265, 159, 467, 102,  39, 101],
       [  9,  19,  21,  26,  22,  36,  15, 131,   8,  23],
       [200, 121,  54,  34,  50,  57,  19,  72, 471, 141],
       [ 60, 168,  29,  69,  31,  38,  39, 138,  99, 407]], dtype=int64)

In [64]:
img_path='/content/bird.jpg'

In [65]:
img_arr=cv2.imread(img_path)

In [66]:
print(img_path)

/content/bird.jpg


In [67]:
print(img_arr)

None


In [68]:
img1_path='/content/dog1.jpg'

In [69]:
img1_arr = cv2.imread(img1_path)

In [72]:
print(img1_arr)

None


In [74]:
classes = ["airplane","automobile","bird","dog","frog","horse"]